title: Juan Mendez
logo: /assets/img/Scrinshot circle.jpg
description: >
  Driven engineer with ample experience in data analysis and investment management, combining analytical expertise and strategic thinking. 
  Highly curious and adaptable, eager to build an exceptional career in the investment industry by embracing challenges, continuous learning, and consistently delivering impactful results.
  <br><br>
  <a href="https://www.linkedin.com/in/juanportet/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <a href="https://github.com/juanmendezportet/data_analyst.github.io/blob/main/assets/Mendz_Juan_Business_Analyst.pdf"> <img src="https://img.shields.io/badge/Resume-lightblue"> </a> 
show_downloads: false
theme: jekyll-theme-minimal


